/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicPublicRouteImport } from './routes/(public)/_public'
import { Route as dashboardDashboardRouteImport } from './routes/(dashboard)/dashboard'
import { Route as publicPublicIndexRouteImport } from './routes/(public)/_public/index'
import { Route as dashboardDashboardIndexRouteImport } from './routes/(dashboard)/dashboard/index'
import { Route as dashboardDashboardScanRouteImport } from './routes/(dashboard)/dashboard/scan'
import { Route as dashboardDashboardResultRouteImport } from './routes/(dashboard)/dashboard/result'
import { Route as dashboardDashboardRecordsRouteImport } from './routes/(dashboard)/dashboard/records'
import { Route as dashboardDashboardProfileRouteImport } from './routes/(dashboard)/dashboard/profile'
import { Route as dashboardDashboardAppointmentsRouteImport } from './routes/(dashboard)/dashboard/appointments'
import { Route as authAuthSignupRouteImport } from './routes/(auth)/auth/signup'
import { Route as authAuthLoginRouteImport } from './routes/(auth)/auth/login'
import { Route as publicPublicOnboardingIndexRouteImport } from './routes/(public)/_public/onboarding/index'
import { Route as dashboardDashboardScanIndexRouteImport } from './routes/(dashboard)/dashboard/scan/index'
import { Route as dashboardDashboardResultIndexRouteImport } from './routes/(dashboard)/dashboard/result/index'
import { Route as dashboardDashboardRecordsIndexRouteImport } from './routes/(dashboard)/dashboard/records/index'
import { Route as dashboardDashboardProfileIndexRouteImport } from './routes/(dashboard)/dashboard/profile/index'
import { Route as dashboardDashboardAppointmentsIndexRouteImport } from './routes/(dashboard)/dashboard/appointments/index'
import { Route as publicPublicOnboardingPaymentRouteImport } from './routes/(public)/_public/onboarding/payment'
import { Route as publicPublicOnboardingBookingRouteImport } from './routes/(public)/_public/onboarding/booking'

const publicRouteImport = createFileRoute('/(public)')()

const publicRoute = publicRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicPublicRoute = publicPublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => publicRoute,
} as any)
const dashboardDashboardRoute = dashboardDashboardRouteImport.update({
  id: '/(dashboard)/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const publicPublicIndexRoute = publicPublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicPublicRoute,
} as any)
const dashboardDashboardIndexRoute = dashboardDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => dashboardDashboardRoute,
} as any)
const dashboardDashboardScanRoute = dashboardDashboardScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => dashboardDashboardRoute,
} as any)
const dashboardDashboardResultRoute =
  dashboardDashboardResultRouteImport.update({
    id: '/result',
    path: '/result',
    getParentRoute: () => dashboardDashboardRoute,
  } as any)
const dashboardDashboardRecordsRoute =
  dashboardDashboardRecordsRouteImport.update({
    id: '/records',
    path: '/records',
    getParentRoute: () => dashboardDashboardRoute,
  } as any)
const dashboardDashboardProfileRoute =
  dashboardDashboardProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => dashboardDashboardRoute,
  } as any)
const dashboardDashboardAppointmentsRoute =
  dashboardDashboardAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => dashboardDashboardRoute,
  } as any)
const authAuthSignupRoute = authAuthSignupRouteImport.update({
  id: '/(auth)/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthLoginRoute = authAuthLoginRouteImport.update({
  id: '/(auth)/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const publicPublicOnboardingIndexRoute =
  publicPublicOnboardingIndexRouteImport.update({
    id: '/onboarding/',
    path: '/onboarding/',
    getParentRoute: () => publicPublicRoute,
  } as any)
const dashboardDashboardScanIndexRoute =
  dashboardDashboardScanIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => dashboardDashboardScanRoute,
  } as any)
const dashboardDashboardResultIndexRoute =
  dashboardDashboardResultIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => dashboardDashboardResultRoute,
  } as any)
const dashboardDashboardRecordsIndexRoute =
  dashboardDashboardRecordsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => dashboardDashboardRecordsRoute,
  } as any)
const dashboardDashboardProfileIndexRoute =
  dashboardDashboardProfileIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => dashboardDashboardProfileRoute,
  } as any)
const dashboardDashboardAppointmentsIndexRoute =
  dashboardDashboardAppointmentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => dashboardDashboardAppointmentsRoute,
  } as any)
const publicPublicOnboardingPaymentRoute =
  publicPublicOnboardingPaymentRouteImport.update({
    id: '/onboarding/payment',
    path: '/onboarding/payment',
    getParentRoute: () => publicPublicRoute,
  } as any)
const publicPublicOnboardingBookingRoute =
  publicPublicOnboardingBookingRouteImport.update({
    id: '/onboarding/booking',
    path: '/onboarding/booking',
    getParentRoute: () => publicPublicRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof dashboardDashboardRouteWithChildren
  '/': typeof publicPublicIndexRoute
  '/auth/login': typeof authAuthLoginRoute
  '/auth/signup': typeof authAuthSignupRoute
  '/dashboard/appointments': typeof dashboardDashboardAppointmentsRouteWithChildren
  '/dashboard/profile': typeof dashboardDashboardProfileRouteWithChildren
  '/dashboard/records': typeof dashboardDashboardRecordsRouteWithChildren
  '/dashboard/result': typeof dashboardDashboardResultRouteWithChildren
  '/dashboard/scan': typeof dashboardDashboardScanRouteWithChildren
  '/dashboard/': typeof dashboardDashboardIndexRoute
  '/onboarding/booking': typeof publicPublicOnboardingBookingRoute
  '/onboarding/payment': typeof publicPublicOnboardingPaymentRoute
  '/dashboard/appointments/': typeof dashboardDashboardAppointmentsIndexRoute
  '/dashboard/profile/': typeof dashboardDashboardProfileIndexRoute
  '/dashboard/records/': typeof dashboardDashboardRecordsIndexRoute
  '/dashboard/result/': typeof dashboardDashboardResultIndexRoute
  '/dashboard/scan/': typeof dashboardDashboardScanIndexRoute
  '/onboarding': typeof publicPublicOnboardingIndexRoute
}
export interface FileRoutesByTo {
  '/auth/login': typeof authAuthLoginRoute
  '/auth/signup': typeof authAuthSignupRoute
  '/dashboard': typeof dashboardDashboardIndexRoute
  '/': typeof publicPublicIndexRoute
  '/onboarding/booking': typeof publicPublicOnboardingBookingRoute
  '/onboarding/payment': typeof publicPublicOnboardingPaymentRoute
  '/dashboard/appointments': typeof dashboardDashboardAppointmentsIndexRoute
  '/dashboard/profile': typeof dashboardDashboardProfileIndexRoute
  '/dashboard/records': typeof dashboardDashboardRecordsIndexRoute
  '/dashboard/result': typeof dashboardDashboardResultIndexRoute
  '/dashboard/scan': typeof dashboardDashboardScanIndexRoute
  '/onboarding': typeof publicPublicOnboardingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(dashboard)/dashboard': typeof dashboardDashboardRouteWithChildren
  '/(public)': typeof publicRouteWithChildren
  '/(public)/_public': typeof publicPublicRouteWithChildren
  '/(auth)/auth/login': typeof authAuthLoginRoute
  '/(auth)/auth/signup': typeof authAuthSignupRoute
  '/(dashboard)/dashboard/appointments': typeof dashboardDashboardAppointmentsRouteWithChildren
  '/(dashboard)/dashboard/profile': typeof dashboardDashboardProfileRouteWithChildren
  '/(dashboard)/dashboard/records': typeof dashboardDashboardRecordsRouteWithChildren
  '/(dashboard)/dashboard/result': typeof dashboardDashboardResultRouteWithChildren
  '/(dashboard)/dashboard/scan': typeof dashboardDashboardScanRouteWithChildren
  '/(dashboard)/dashboard/': typeof dashboardDashboardIndexRoute
  '/(public)/_public/': typeof publicPublicIndexRoute
  '/(public)/_public/onboarding/booking': typeof publicPublicOnboardingBookingRoute
  '/(public)/_public/onboarding/payment': typeof publicPublicOnboardingPaymentRoute
  '/(dashboard)/dashboard/appointments/': typeof dashboardDashboardAppointmentsIndexRoute
  '/(dashboard)/dashboard/profile/': typeof dashboardDashboardProfileIndexRoute
  '/(dashboard)/dashboard/records/': typeof dashboardDashboardRecordsIndexRoute
  '/(dashboard)/dashboard/result/': typeof dashboardDashboardResultIndexRoute
  '/(dashboard)/dashboard/scan/': typeof dashboardDashboardScanIndexRoute
  '/(public)/_public/onboarding/': typeof publicPublicOnboardingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/'
    | '/auth/login'
    | '/auth/signup'
    | '/dashboard/appointments'
    | '/dashboard/profile'
    | '/dashboard/records'
    | '/dashboard/result'
    | '/dashboard/scan'
    | '/dashboard/'
    | '/onboarding/booking'
    | '/onboarding/payment'
    | '/dashboard/appointments/'
    | '/dashboard/profile/'
    | '/dashboard/records/'
    | '/dashboard/result/'
    | '/dashboard/scan/'
    | '/onboarding'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth/login'
    | '/auth/signup'
    | '/dashboard'
    | '/'
    | '/onboarding/booking'
    | '/onboarding/payment'
    | '/dashboard/appointments'
    | '/dashboard/profile'
    | '/dashboard/records'
    | '/dashboard/result'
    | '/dashboard/scan'
    | '/onboarding'
  id:
    | '__root__'
    | '/(dashboard)/dashboard'
    | '/(public)'
    | '/(public)/_public'
    | '/(auth)/auth/login'
    | '/(auth)/auth/signup'
    | '/(dashboard)/dashboard/appointments'
    | '/(dashboard)/dashboard/profile'
    | '/(dashboard)/dashboard/records'
    | '/(dashboard)/dashboard/result'
    | '/(dashboard)/dashboard/scan'
    | '/(dashboard)/dashboard/'
    | '/(public)/_public/'
    | '/(public)/_public/onboarding/booking'
    | '/(public)/_public/onboarding/payment'
    | '/(dashboard)/dashboard/appointments/'
    | '/(dashboard)/dashboard/profile/'
    | '/(dashboard)/dashboard/records/'
    | '/(dashboard)/dashboard/result/'
    | '/(dashboard)/dashboard/scan/'
    | '/(public)/_public/onboarding/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  dashboardDashboardRoute: typeof dashboardDashboardRouteWithChildren
  publicRoute: typeof publicRouteWithChildren
  authAuthLoginRoute: typeof authAuthLoginRoute
  authAuthSignupRoute: typeof authAuthSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)': {
      id: '/(public)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/_public': {
      id: '/(public)/_public'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicPublicRouteImport
      parentRoute: typeof publicRoute
    }
    '/(dashboard)/dashboard': {
      id: '/(dashboard)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof dashboardDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/_public/': {
      id: '/(public)/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicPublicIndexRouteImport
      parentRoute: typeof publicPublicRoute
    }
    '/(dashboard)/dashboard/': {
      id: '/(dashboard)/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof dashboardDashboardIndexRouteImport
      parentRoute: typeof dashboardDashboardRoute
    }
    '/(dashboard)/dashboard/scan': {
      id: '/(dashboard)/dashboard/scan'
      path: '/scan'
      fullPath: '/dashboard/scan'
      preLoaderRoute: typeof dashboardDashboardScanRouteImport
      parentRoute: typeof dashboardDashboardRoute
    }
    '/(dashboard)/dashboard/result': {
      id: '/(dashboard)/dashboard/result'
      path: '/result'
      fullPath: '/dashboard/result'
      preLoaderRoute: typeof dashboardDashboardResultRouteImport
      parentRoute: typeof dashboardDashboardRoute
    }
    '/(dashboard)/dashboard/records': {
      id: '/(dashboard)/dashboard/records'
      path: '/records'
      fullPath: '/dashboard/records'
      preLoaderRoute: typeof dashboardDashboardRecordsRouteImport
      parentRoute: typeof dashboardDashboardRoute
    }
    '/(dashboard)/dashboard/profile': {
      id: '/(dashboard)/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof dashboardDashboardProfileRouteImport
      parentRoute: typeof dashboardDashboardRoute
    }
    '/(dashboard)/dashboard/appointments': {
      id: '/(dashboard)/dashboard/appointments'
      path: '/appointments'
      fullPath: '/dashboard/appointments'
      preLoaderRoute: typeof dashboardDashboardAppointmentsRouteImport
      parentRoute: typeof dashboardDashboardRoute
    }
    '/(auth)/auth/signup': {
      id: '/(auth)/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof authAuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/auth/login': {
      id: '/(auth)/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof authAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/_public/onboarding/': {
      id: '/(public)/_public/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof publicPublicOnboardingIndexRouteImport
      parentRoute: typeof publicPublicRoute
    }
    '/(dashboard)/dashboard/scan/': {
      id: '/(dashboard)/dashboard/scan/'
      path: '/'
      fullPath: '/dashboard/scan/'
      preLoaderRoute: typeof dashboardDashboardScanIndexRouteImport
      parentRoute: typeof dashboardDashboardScanRoute
    }
    '/(dashboard)/dashboard/result/': {
      id: '/(dashboard)/dashboard/result/'
      path: '/'
      fullPath: '/dashboard/result/'
      preLoaderRoute: typeof dashboardDashboardResultIndexRouteImport
      parentRoute: typeof dashboardDashboardResultRoute
    }
    '/(dashboard)/dashboard/records/': {
      id: '/(dashboard)/dashboard/records/'
      path: '/'
      fullPath: '/dashboard/records/'
      preLoaderRoute: typeof dashboardDashboardRecordsIndexRouteImport
      parentRoute: typeof dashboardDashboardRecordsRoute
    }
    '/(dashboard)/dashboard/profile/': {
      id: '/(dashboard)/dashboard/profile/'
      path: '/'
      fullPath: '/dashboard/profile/'
      preLoaderRoute: typeof dashboardDashboardProfileIndexRouteImport
      parentRoute: typeof dashboardDashboardProfileRoute
    }
    '/(dashboard)/dashboard/appointments/': {
      id: '/(dashboard)/dashboard/appointments/'
      path: '/'
      fullPath: '/dashboard/appointments/'
      preLoaderRoute: typeof dashboardDashboardAppointmentsIndexRouteImport
      parentRoute: typeof dashboardDashboardAppointmentsRoute
    }
    '/(public)/_public/onboarding/payment': {
      id: '/(public)/_public/onboarding/payment'
      path: '/onboarding/payment'
      fullPath: '/onboarding/payment'
      preLoaderRoute: typeof publicPublicOnboardingPaymentRouteImport
      parentRoute: typeof publicPublicRoute
    }
    '/(public)/_public/onboarding/booking': {
      id: '/(public)/_public/onboarding/booking'
      path: '/onboarding/booking'
      fullPath: '/onboarding/booking'
      preLoaderRoute: typeof publicPublicOnboardingBookingRouteImport
      parentRoute: typeof publicPublicRoute
    }
  }
}

interface dashboardDashboardAppointmentsRouteChildren {
  dashboardDashboardAppointmentsIndexRoute: typeof dashboardDashboardAppointmentsIndexRoute
}

const dashboardDashboardAppointmentsRouteChildren: dashboardDashboardAppointmentsRouteChildren =
  {
    dashboardDashboardAppointmentsIndexRoute:
      dashboardDashboardAppointmentsIndexRoute,
  }

const dashboardDashboardAppointmentsRouteWithChildren =
  dashboardDashboardAppointmentsRoute._addFileChildren(
    dashboardDashboardAppointmentsRouteChildren,
  )

interface dashboardDashboardProfileRouteChildren {
  dashboardDashboardProfileIndexRoute: typeof dashboardDashboardProfileIndexRoute
}

const dashboardDashboardProfileRouteChildren: dashboardDashboardProfileRouteChildren =
  {
    dashboardDashboardProfileIndexRoute: dashboardDashboardProfileIndexRoute,
  }

const dashboardDashboardProfileRouteWithChildren =
  dashboardDashboardProfileRoute._addFileChildren(
    dashboardDashboardProfileRouteChildren,
  )

interface dashboardDashboardRecordsRouteChildren {
  dashboardDashboardRecordsIndexRoute: typeof dashboardDashboardRecordsIndexRoute
}

const dashboardDashboardRecordsRouteChildren: dashboardDashboardRecordsRouteChildren =
  {
    dashboardDashboardRecordsIndexRoute: dashboardDashboardRecordsIndexRoute,
  }

const dashboardDashboardRecordsRouteWithChildren =
  dashboardDashboardRecordsRoute._addFileChildren(
    dashboardDashboardRecordsRouteChildren,
  )

interface dashboardDashboardResultRouteChildren {
  dashboardDashboardResultIndexRoute: typeof dashboardDashboardResultIndexRoute
}

const dashboardDashboardResultRouteChildren: dashboardDashboardResultRouteChildren =
  {
    dashboardDashboardResultIndexRoute: dashboardDashboardResultIndexRoute,
  }

const dashboardDashboardResultRouteWithChildren =
  dashboardDashboardResultRoute._addFileChildren(
    dashboardDashboardResultRouteChildren,
  )

interface dashboardDashboardScanRouteChildren {
  dashboardDashboardScanIndexRoute: typeof dashboardDashboardScanIndexRoute
}

const dashboardDashboardScanRouteChildren: dashboardDashboardScanRouteChildren =
  {
    dashboardDashboardScanIndexRoute: dashboardDashboardScanIndexRoute,
  }

const dashboardDashboardScanRouteWithChildren =
  dashboardDashboardScanRoute._addFileChildren(
    dashboardDashboardScanRouteChildren,
  )

interface dashboardDashboardRouteChildren {
  dashboardDashboardAppointmentsRoute: typeof dashboardDashboardAppointmentsRouteWithChildren
  dashboardDashboardProfileRoute: typeof dashboardDashboardProfileRouteWithChildren
  dashboardDashboardRecordsRoute: typeof dashboardDashboardRecordsRouteWithChildren
  dashboardDashboardResultRoute: typeof dashboardDashboardResultRouteWithChildren
  dashboardDashboardScanRoute: typeof dashboardDashboardScanRouteWithChildren
  dashboardDashboardIndexRoute: typeof dashboardDashboardIndexRoute
}

const dashboardDashboardRouteChildren: dashboardDashboardRouteChildren = {
  dashboardDashboardAppointmentsRoute:
    dashboardDashboardAppointmentsRouteWithChildren,
  dashboardDashboardProfileRoute: dashboardDashboardProfileRouteWithChildren,
  dashboardDashboardRecordsRoute: dashboardDashboardRecordsRouteWithChildren,
  dashboardDashboardResultRoute: dashboardDashboardResultRouteWithChildren,
  dashboardDashboardScanRoute: dashboardDashboardScanRouteWithChildren,
  dashboardDashboardIndexRoute: dashboardDashboardIndexRoute,
}

const dashboardDashboardRouteWithChildren =
  dashboardDashboardRoute._addFileChildren(dashboardDashboardRouteChildren)

interface publicPublicRouteChildren {
  publicPublicIndexRoute: typeof publicPublicIndexRoute
  publicPublicOnboardingBookingRoute: typeof publicPublicOnboardingBookingRoute
  publicPublicOnboardingPaymentRoute: typeof publicPublicOnboardingPaymentRoute
  publicPublicOnboardingIndexRoute: typeof publicPublicOnboardingIndexRoute
}

const publicPublicRouteChildren: publicPublicRouteChildren = {
  publicPublicIndexRoute: publicPublicIndexRoute,
  publicPublicOnboardingBookingRoute: publicPublicOnboardingBookingRoute,
  publicPublicOnboardingPaymentRoute: publicPublicOnboardingPaymentRoute,
  publicPublicOnboardingIndexRoute: publicPublicOnboardingIndexRoute,
}

const publicPublicRouteWithChildren = publicPublicRoute._addFileChildren(
  publicPublicRouteChildren,
)

interface publicRouteChildren {
  publicPublicRoute: typeof publicPublicRouteWithChildren
}

const publicRouteChildren: publicRouteChildren = {
  publicPublicRoute: publicPublicRouteWithChildren,
}

const publicRouteWithChildren =
  publicRoute._addFileChildren(publicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  dashboardDashboardRoute: dashboardDashboardRouteWithChildren,
  publicRoute: publicRouteWithChildren,
  authAuthLoginRoute: authAuthLoginRoute,
  authAuthSignupRoute: authAuthSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
